/* Generated By:JavaCC: Do not edit this line. S1414jConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface S1414jConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRINTLN = 6;
  /** RegularExpression Id. */
  int PRINT = 7;
  /** RegularExpression Id. */
  int READINT = 8;
  /** RegularExpression Id. */
  int UNSIGNED = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int VAR_INCREMENT = 11;
  /** RegularExpression Id. */
  int VAR_DECREMENT = 12;
  /** RegularExpression Id. */
  int INCREMENT_VAR = 13;
  /** RegularExpression Id. */
  int DECREMENT_VAR = 14;
  /** RegularExpression Id. */
  int ID = 15;
  /** RegularExpression Id. */
  int ASSIGN = 16;
  /** RegularExpression Id. */
  int SEMICOLON = 17;
  /** RegularExpression Id. */
  int LEFTPAREN = 18;
  /** RegularExpression Id. */
  int RIGHTPAREN = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int TIMES = 22;
  /** RegularExpression Id. */
  int DIVIDE = 23;
  /** RegularExpression Id. */
  int LEFTBRACE = 24;
  /** RegularExpression Id. */
  int RIGHTBRACE = 25;
  /** RegularExpression Id. */
  int ERROR = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 5>",
    "\"println\"",
    "\"print\"",
    "\"readint\"",
    "<UNSIGNED>",
    "<STRING>",
    "<VAR_INCREMENT>",
    "<VAR_DECREMENT>",
    "<INCREMENT_VAR>",
    "<DECREMENT_VAR>",
    "<ID>",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"{\"",
    "\"}\"",
    "<ERROR>",
  };

}
