/* Generated By:JavaCC: Do not edit this line. S5j.java */
import java.io.*;
import java.util.ArrayList;

//======================================================
interface SymTabConstants
{
        int LOCAL = 0;
        int GLOBALVARIABLE = 1;
        int EXTERNVARIABLE = 2;
        int FUNCTIONDEFINITION = 3;
        int FUNCTIONCALL = 4;
}
//======================================================
class S5j implements SymTabConstants, S5jConstants {
  private PrintWriter outFile;
  private S5jSymTab st;
  private S5jCodeGen cg;
  //-----------------------------------------
  public static void main(String[] args) throws
                                             IOException
  {
    System.out.println("S5j compiler written by Hung PHAN, Shir Lie Ooi, Sen Shen");

    if (args.length != 1)
    {
      System.err.println("Wrong number cmd line args");
      System.exit(1);
    }

    // build input and output file names
    String inFileName = args[0] + ".s";
    String outFileName = args[0] + ".a";

    // construct file objects
    FileInputStream inFile =
                       new FileInputStream(inFileName);
    PrintWriter outFile = new PrintWriter(outFileName);

    // identify compiler/author in output file
    outFile.println("; from S5j compiler written by Hung PHAN, Shir Lie Ooi, Sen Shen");

    // construct objects that make up compiler
    S5jSymTab st = new S5jSymTab();
    S5jCodeGen cg = new S5jCodeGen(outFile, st);
    S5j parser = new S5j(inFile);

    // initialize parser's instance variables
    parser.outFile = outFile;
    parser.st = st;
    parser.cg = cg;

    try
    {
      parser.program();
    }
    catch(ParseException e)
    {
      System.err.println(e.getMessage());
      outFile.println(e.getMessage());
      outFile.close();
      System.exit(1);
    }

    outFile.close();
  }
  //-----------------------------------------
  // If COMMON_TOKEN_ACTION is true, the token manager 
  // calls makeComment for each token to create the
  // token trace.
  //
  public void makeComment(Token t)
  {
    outFile.printf(
      "; kd=%3d bL=%3d bC=%3d eL=%3d eC=%3d im= %s%n",
       t.kind, t.beginLine, t.beginColumn, t.endLine,
       t.endColumn, t.image);
  }

  // second makeComment method
  public void makeComment(Token t1, Token t2)
  {
        outFile.print("; "); // start comment
        while (t1 != t2)
        {
                outFile.print(t1.image + " ");
                t1 = t1.next;
        }
        outFile.println(); // terminate comment
  }

  //third makeComment method
  public void makeComment(String s)
  {
        outFile.println("; " + s);
  }
  //-----------------------------------------
  // Construct and return an exception that contains
  // a message consisting of the image of the current
  // token, its location, and the expected tokens.
  //
  public ParseException genEx(String errorMessage)
  {
    return new ParseException("Encountered \u005c"" +
      getToken(1).image + "\u005c" on line " +
      getToken(1).beginLine + ", column " +
      getToken(1).beginColumn + "." +
      System.getProperty("line.separator") +
      errorMessage);
  }

// Translation grammar for S5j and S5 ==================
  final public void program() throws ParseException {
    programUnitList();
    cg.endCode();
    jj_consume_token(0);
  }

//------------------------------
  final public void programUnitList() throws ParseException {
    if (getToken(1).kind == EOF) {if (true) return;}
    programUnit();
    programUnitList();
  }

//------------------------------
  final public void programUnit() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EXTERN:
        externDeclaration();
        break;
      case INT:
        globalDeclaration();
        break;
      case VOID:
        functionDefinition();
        break;
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
    System.err.println(e.getMessage());
        cg.emitString(e.getMessage());
    while(getToken(1).kind != SEMICOLON &&
    getToken(1).kind != EOF)
        getNextToken();
    if(getToken(1).kind != EOF)
        getNextToken();
    }
  }

//------------------------------
  final public void externDeclaration() throws ParseException {
                           Token t;
    jj_consume_token(EXTERN);
    jj_consume_token(INT);
    t = jj_consume_token(ID);
    st.enter(this, t.image, 0, EXTERNVARIABLE);
    cg.emitInstruction("extern", t.image);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      jj_consume_token(COMMA);
      t = jj_consume_token(ID);
       st.enter(this, t.image, 0, EXTERNVARIABLE);
       cg.emitInstruction("extern", t.image);
    }
    jj_consume_token(SEMICOLON);
  }

//------------------------------
  final public void globalDeclaration() throws ParseException {
    jj_consume_token(INT);
    global();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      jj_consume_token(COMMA);
      global();
    }
    jj_consume_token(SEMICOLON);
  }

//------------------------------
  final public void global() throws ParseException {
                Token t1, t2; String initVal;
    t1 = jj_consume_token(ID);
    cg.emitInstruction("public", t1.image);
    initVal="0";
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGN:
      jj_consume_token(ASSIGN);
       initVal = "";
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PLUS:
          jj_consume_token(PLUS);
          break;
        case MINUS:
          jj_consume_token(MINUS);
                         initVal = "-";
          break;
        default:
          jj_la1[3] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[4] = jj_gen;
        ;
      }
      t2 = jj_consume_token(UNSIGNED);
       initVal = initVal + t2.image;
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    st.enter(this, t1.image, 0, GLOBALVARIABLE);
    cg.emitdw(t1.image, initVal);
  }

//------------------------------
  final public void functionDefinition() throws ParseException {
                            Token t;
    jj_consume_token(VOID);
    t = jj_consume_token(ID);
    cg.emitString(
      "; =============== start of function " + t.image);
    st.enter(this, t.image, 0, FUNCTIONDEFINITION);
    cg.emitInstruction("public", t.image);
    cg.emitLabel(t.image);
    jj_consume_token(LEFTPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
      parameterList();
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    jj_consume_token(RIGHTPAREN);
    jj_consume_token(LEFTBRACE);
    cg.emitInstruction("esba");
    localDeclarations();
    statementList();
    jj_consume_token(RIGHTBRACE);
    cg.emitInstruction("reba");
    cg.emitInstruction("ret");
    cg.emitString(
      "; =============== end of function " + t.image);
    st.localRemove();
  }

//------------------------------
  final public void parameterList() throws ParseException {
                       Token t; int p;
    t = parameter();
    p = parameterR();
    st.enter(this, t.image, p, LOCAL);
  }

//------------------------------
  final public Token parameter() throws ParseException {
                    Token t;
    jj_consume_token(INT);
    t = jj_consume_token(ID);
    {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

//------------------------------
  final public int parameterR() throws ParseException {
                   Token t; int p;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      t = parameter();
      p = parameterR();
    st.enter(this, t.image, p, LOCAL);
    {if (true) return p + 1;}
      break;
    default:
      jj_la1[7] = jj_gen;
    {if (true) return 2;}
    }
    throw new Error("Missing return statement in function");
  }

//------------------------------
  final public void localDeclarations() throws ParseException {
                           int relativeAddress = -1;
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INT:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_3;
      }
      jj_consume_token(INT);
      local(relativeAddress--);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[9] = jj_gen;
          break label_4;
        }
        jj_consume_token(COMMA);
        local(relativeAddress--);
      }
      jj_consume_token(SEMICOLON);
    }
  }

//------------------------------
  final public void local(int relativeAddress) throws ParseException {
                                  Token t; String sign;
    t = jj_consume_token(ID);
    st.enter(this, t.image, relativeAddress, LOCAL);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGN:
      jj_consume_token(ASSIGN);
          sign = "";
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PLUS:
          jj_consume_token(PLUS);
          break;
        case MINUS:
          jj_consume_token(MINUS);
                            sign = "-";
          break;
        default:
          jj_la1[10] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      default:
        jj_la1[11] = jj_gen;
        ;
      }
      t = jj_consume_token(UNSIGNED);
          cg.emitInstruction("pwc", sign + t.image);
      break;
    default:
      jj_la1[12] = jj_gen;
       cg.emitInstruction("asp", "-1");
    }
  }

//------------------------------
  final public void statementList() throws ParseException {
    if (getToken(1).kind == RIGHTBRACE) {if (true) return;}
    statement();
    statementList();
  }

//------------------------------
  final public void statement() throws ParseException {
                   Token t; boolean outComment;
    try {
     t = getToken(1);
         outComment = true;
      if (jj_2_1(2)) {
        assignmentStatement();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ID:
          functionCall();
          break;
        case PRINTLN:
          printlnStatement();
          break;
        case PRINT:
          printStatement();
          break;
        case SEMICOLON:
          nullStatement();
          break;
        case LEFTBRACE:
          compoundStatement();
            outComment = false;
          break;
        case READINT:
          readintStatement();
          break;
        case WHILE:
          whileStatement();
          break;
        case IF:
          ifStatement();
          break;
        case DO:
          doWhileStatement();
          break;
        default:
          jj_la1[13] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
         if (outComment) makeComment(t, getToken(1));
    } catch (ParseException e) {
    System.err.println(e.getMessage());
        cg.emitString(e.getMessage());
    while(getToken(1).kind != SEMICOLON &&
    getToken(1).kind != EOF)
        getNextToken();
    if(getToken(1).kind != EOF)
        getNextToken();
    }
  }

//------------------------------
  final public void assignmentStatement() throws ParseException {
                             Token t; int index;
    t = jj_consume_token(ID);
    index=st.find(this, t.image);
    cg.pushAddress(index);
    jj_consume_token(ASSIGN);
    assignmentTail();
    cg.emitInstruction("stav");
  }

//------------------------------
  final public void assignmentTail() throws ParseException {
                        Token t; int index;
    if (jj_2_2(2)) {
      t = jj_consume_token(ID);
    index=st.find(this, t.image);
    cg.pushAddress(index);
      jj_consume_token(ASSIGN);
      assignmentTail();
    cg.emitInstruction("dupe");
    cg.emitInstruction("rot");
    cg.emitInstruction("stav");
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case UNSIGNED:
      case ID:
      case LEFTPAREN:
      case PLUS:
      case MINUS:
        expr();
        jj_consume_token(SEMICOLON);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

//------------------------------
  final public void printlnStatement() throws ParseException {
    jj_consume_token(PRINTLN);
    jj_consume_token(LEFTPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case UNSIGNED:
    case ID:
    case LEFTPAREN:
    case PLUS:
    case MINUS:
    case STRING:
      printArg();
      break;
    default:
      jj_la1[15] = jj_gen;

    }
    cg.emitInstruction("pc", "'\u005c\u005cn'");
    cg.emitInstruction("aout");
    jj_consume_token(RIGHTPAREN);
    jj_consume_token(SEMICOLON);
  }

  final public void printArg() throws ParseException {
                  Token t; String label;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
      t = jj_consume_token(STRING);
         label=cg.getLabel();
         cg.emitInstruction("pc", label);
         cg.emitInstruction("sout");
         cg.emitdw("^"+label, t.image);
      break;
    case UNSIGNED:
    case ID:
    case LEFTPAREN:
    case PLUS:
    case MINUS:
      expr();
         cg.emitInstruction("dout");
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//------------------------------
  final public void printStatement() throws ParseException {
    jj_consume_token(PRINT);
    jj_consume_token(LEFTPAREN);
    printArg();
    jj_consume_token(RIGHTPAREN);
    jj_consume_token(SEMICOLON);
  }

//------------------------------
  final public void nullStatement() throws ParseException {
    jj_consume_token(SEMICOLON);
  }

//------------------------------
  final public void compoundStatement() throws ParseException {
    jj_consume_token(LEFTBRACE);
    makeComment("{");
    compoundList();
    jj_consume_token(RIGHTBRACE);
    makeComment("}");
  }

//------------------------------
  final public void compoundList() throws ParseException {
          if (getToken(1).kind == RIGHTBRACE)
                  {if (true) return;}
    statement();
    compoundList();
  }

//------------------------------
  final public void readintStatement() throws ParseException {
                          Token t; int index;
    jj_consume_token(READINT);
    jj_consume_token(LEFTPAREN);
    t = jj_consume_token(ID);
    index=st.find(this, t.image);
    cg.pushAddress(index);
    cg.emitInstruction("din");
    cg.emitInstruction("stav");
    jj_consume_token(RIGHTPAREN);
    jj_consume_token(SEMICOLON);
  }

//------------------------------
  final public void whileStatement() throws ParseException {
                        String label1, label2; Token t;
    jj_consume_token(WHILE);
    label1=cg.getLabel();
    cg.emitLabel(label1);
    jj_consume_token(LEFTPAREN);
    expr();
    jj_consume_token(RIGHTPAREN);
    label2=cg.getLabel();
    cg.emitInstruction("jz", label2);
    statement();
    cg.emitInstruction("ja", label1);
    cg.emitLabel(label2);
  }

//------------------------------
  final public void ifStatement() throws ParseException {
                     String label1;
    jj_consume_token(IF);
    jj_consume_token(LEFTPAREN);
    expr();
    jj_consume_token(RIGHTPAREN);
    label1=cg.getLabel();
    cg.emitInstruction("jz", label1);
    statement();
    elsePart(label1);
  }

//------------------------------
  final public void elsePart(String label1) throws ParseException {
                               String label2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
    label2=cg.getLabel();
    cg.emitInstruction("ja", label2);
    cg.emitLabel(label1);
      statement();
    cg.emitLabel(label2);
      break;
    default:
      jj_la1[17] = jj_gen;
    cg.emitLabel(label1);
    }
  }

//------------------------------
  final public void doWhileStatement() throws ParseException {
                          String label;
    jj_consume_token(DO);
    label = cg.getLabel();
    cg.emitLabel(label);
    statement();
    jj_consume_token(WHILE);
    jj_consume_token(LEFTPAREN);
    expr();
    jj_consume_token(RIGHTPAREN);
    cg.emitInstruction("jnz", label);
    jj_consume_token(SEMICOLON);
  }

//------------------------------
  final public void functionCall() throws ParseException {
                      Token t; int count;
    t = jj_consume_token(ID);
    st.enter(this, t.image, 0, FUNCTIONCALL);
    jj_consume_token(LEFTPAREN);
    count = 0;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case UNSIGNED:
    case ID:
    case LEFTPAREN:
    case PLUS:
    case MINUS:
      count = argumentList();
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    cg.emitInstruction("call", t.image);
      if (count > 0)
         cg.emitInstruction("asp",
                               Integer.toString(count));
    jj_consume_token(RIGHTPAREN);
    jj_consume_token(SEMICOLON);
  }

//------------------------------
  final public int argumentList() throws ParseException {
                     int count;
    expr();
    count = 1;
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[19] = jj_gen;
        break label_5;
      }
      jj_consume_token(COMMA);
      expr();
       count++;
    }
    {if (true) return count;}
    throw new Error("Missing return statement in function");
  }

//------------------------------
  final public void expr() throws ParseException {
    term();
    termList();
  }

//------------------------------
  final public void termList() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
      jj_consume_token(PLUS);
      term();
    cg.emitInstruction("add");
      termList();
      break;
    case MINUS:
      jj_consume_token(MINUS);
      term();
    cg.emitInstruction("sub");
      termList();
      break;
    default:
      jj_la1[20] = jj_gen;

    }
  }

//------------------------------
  final public void term() throws ParseException {
    factor();
    factorList();
  }

//------------------------------
  final public void factorList() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TIMES:
      jj_consume_token(TIMES);
      factor();
    cg.emitInstruction("mult");
      factorList();
      break;
    case DIVIDE:
      jj_consume_token(DIVIDE);
      factor();
    cg.emitInstruction("div");
      factorList();
      break;
    default:
      jj_la1[21] = jj_gen;

    }
  }

//------------------------------
  final public void factor() throws ParseException {
                Token t; int index;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case UNSIGNED:
      t = jj_consume_token(UNSIGNED);
    if (t.image.length() > 5 ||
                        Integer.parseInt(t.image) > 32767)
                {if (true) throw genEx("Expecting integer (-32768 to 32767)");}
    cg.emitInstruction("pwc", t.image);
      break;
    case ID:
      t = jj_consume_token(ID);
    index=st.find(this, t.image);
    cg.push(index);
      break;
    case LEFTPAREN:
      jj_consume_token(LEFTPAREN);
      expr();
      jj_consume_token(RIGHTPAREN);
      break;
    case PLUS:
      jj_consume_token(PLUS);
      factor();
      break;
    case MINUS:
      jj_consume_token(MINUS);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case UNSIGNED:
        t = jj_consume_token(UNSIGNED);
       if (t.image.length() > 5 ||
                        Integer.parseInt(t.image) > 32767)
                {if (true) throw genEx("Expecting integer (-32768 to 32767)");}
       cg.emitInstruction("pwc", "-" + t.image);
        break;
      case ID:
        t = jj_consume_token(ID);
       index=st.find(this, t.image);
       cg.push(index);
       cg.emitInstruction("neg");
        break;
      case LEFTPAREN:
        jj_consume_token(LEFTPAREN);
        expr();
        jj_consume_token(RIGHTPAREN);
       cg.emitInstruction("neg");
        break;
      case PLUS:
        label_6:
        while (true) {
          jj_consume_token(PLUS);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case PLUS:
            ;
            break;
          default:
            jj_la1[22] = jj_gen;
            break label_6;
          }
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case MINUS:
          jj_consume_token(MINUS);
          factor();
          break;
        case UNSIGNED:
        case ID:
        case LEFTPAREN:
        case PLUS:
          factor();
          cg.emitInstruction("neg");
          break;
        default:
          jj_la1[23] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
      case MINUS:
        jj_consume_token(MINUS);
        factor();
        break;
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_3R_7() {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_7()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public S5jTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[26];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x380,0x20000000,0x20000000,0x1800000,0x1800000,0x80000,0x100,0x20000000,0x100,0x20000000,0x1800000,0x1800000,0x80000,0x815f400,0x1a60000,0x1a60000,0x1a60000,0x800,0x1a60000,0x20000000,0x1800000,0x6000000,0x800000,0x1a60000,0x1a60000,0x1a60000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x10,0x10,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[2];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public S5j(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public S5j(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new S5jTokenManager(this, jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public S5j(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new S5jTokenManager(this, jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public S5j(S5jTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(S5jTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[38];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 26; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 38; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 2; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}                                          // end of S5j
//======================================================
class S5jSymTab implements SymTabConstants
{
  private ArrayList<String> symbol;
  private ArrayList<Integer> relAdd;
  private ArrayList<Integer> category;
  //-----------------------------------------
  public S5jSymTab()
  {
    symbol = new ArrayList<String>();
    relAdd = new ArrayList<Integer>();
    category = new ArrayList<Integer>();
  }
  //-----------------------------------------
  public void enter(S5j s, String sym, int ra, int cat) throws ParseException
  {
          int index = symbol.indexOf(sym);
          if (index >= 0) {
                  int oldCat = category.get(index);
                  if(cat == FUNCTIONCALL &&
                                  oldCat >= FUNCTIONDEFINITION) {
                          return;
                  }
                  if(cat == FUNCTIONDEFINITION &&
                                  oldCat == FUNCTIONCALL) {
                          category.set(index, FUNCTIONDEFINITION);
                          return;
                  }
                  if(cat == LOCAL && (oldCat == GLOBALVARIABLE
                                  || oldCat == EXTERNVARIABLE));
                  else throw s.genEx("Duplicate symbol");
          }
          symbol.add(sym);
          relAdd.add(ra);
          category.add(cat);
  }
  //-----------------------------------------
  public int find(S5j s, String sym) throws ParseException
  {
          int index = symbol.lastIndexOf(sym);
          if(index >= 0)
                  return index;
          else
                  throw s.genEx("Undeclared symbol");
  }
  //-----------------------------------------
  public String getSymbol(int i)
  {
    return symbol.get(i);
  }
  //-----------------------------------------
  public int getRelAdd(int index)
  {
          return relAdd.get(index);
  }
  //-----------------------------------------
  public int getCategory(int index)
  {
          return category.get(index);
  }
  //-----------------------------------------
  public int getSize()
  {
    return symbol.size();
  }
  //-----------------------------------------
  public void localRemove()
  {
          for (int i = symbol.size() - 1; i >= 0; i--)
                  if(category.get(i) == LOCAL)
                  {
                          symbol.remove(i);
                          relAdd.remove(i);
                          category.remove(i);
                  }
  }
}                                    // end of S5jSymTab
//======================================================
class S5jCodeGen implements SymTabConstants
{
  private PrintWriter outFile;
  private S5jSymTab st;
  private int labelNumber;
  //-----------------------------------------
  public S5jCodeGen(PrintWriter outFile, S5jSymTab st)
  {
    this.outFile = outFile;
    this.st = st;
    this.labelNumber = 0;
  }
  //-----------------------------------------
  public void emitInstruction(String op)
  {
    outFile.printf("          %-6s%n", op);
  }
  //-----------------------------------------
  public void emitInstruction(String op, String opnd)
  {
    outFile.printf(
                  "          %-6s      %s%n", op, opnd);
  }
  //-----------------------------------------
  public void emitdw(String label, String value)
  {
    outFile.printf(
             "%-9s dw        %s%n", label + ":", value);
  }
  //-----------------------------------------
  public void emitString(String s)
  {
        outFile.println(s);
  }
  //-----------------------------------------
  public void emitLabel(String label)
  {
          outFile.printf(label + ":");
  }
  //-----------------------------------------
  public String getLabel()
  {
          return "@L" + labelNumber++;
  }
  //-----------------------------------------  
  public void push(int p)
  {
          if(st.getCategory(p) != LOCAL)
                  emitInstruction("p", st.getSymbol(p));
          else
                  emitInstruction("pr", ""+st.getRelAdd(p));
  }
  //----------------------------------------- 
  public void pushAddress(int p)
  {
          if(st.getCategory(p) != LOCAL)
                  emitInstruction("pc", st.getSymbol(p));
          else
                  emitInstruction("cora", ""+st.getRelAdd(p));
  }
  //-----------------------------------------
  public void endCode()
  {
    outFile.println();
    emitInstruction("halt");

    int size = st.getSize();
    // emit dw for each symbol in the symbol table
    for (int i=0; i < size; i++)
        if(st.getCategory(i) == FUNCTIONCALL)
                emitInstruction("extern", st.getSymbol(i));
  }
}
